# Generated by Django 5.0.7 on 2024-08-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
    ]
